###
GET   http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs/66ec297242bf5fe35cbddf66/comments
content-type: application/json

{
  "content": "this is first comment"
}


###
DELETE http://localhost:3001/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1lbGlrZWRpQGdtYWlsLmNvbSIsImlkIjoiNjZhMGQyMTMyMTFhODIyZDI5ZDc3ZWVkIiwiaWF0IjoxNzIxODIzMDA3fQ.kxg_FyfL-4aebx8kzFJFEHuL6Hvwf0JNnMsDQwyPmUk

###
DELETE http://localhost:3001/api/blogs/66a37eab7ecb5e2e0af9c90b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1lbGlrZWRpQGdtYWlsLmNvbSIsImlkIjoiNjZhMGQyMTMyMTFhODIyZDI5ZDc3ZWVkIiwiaWF0IjoxNzIxODIzMDA3fQ.kxg_FyfL-4aebx8kzFJFEHuL6Hvwf0JNnMsDQwyPmUk


###
DELETE http://localhost:3001/api/blogs/66a0d73849a04f631961a91a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1lbGlrZWRpQGdtYWlsLmNvbSIsImlkIjoiNjZhMGQyMTMyMTFhODIyZDI5ZDc3ZWVkIiwiaWF0IjoxNzIxODIzMDA3fQ.kxg_FyfL-4aebx8kzFJFEHuL6Hvwf0JNnMsDQwyPmUk

###
DELETE http://localhost:3001/api/blogs/66a0e8345ba53a599d01b915
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3RAZ21haWwuY29tIiwiaWQiOiI2NmEwZDIxNTIxMWE4MjJkMjlkNzdlZWYiLCJpYXQiOjE3MjE4MjI4MTR9.5-5jRwtH6CnegnmpOvpLzZANacS4-0KuurHPvDujjg8
###
POST http://localhost:3001/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1lbGlrZWRpQGdtYWlsLmNvbSIsImlkIjoiNjZhMGQyMTMyMTFhODIyZDI5ZDc3ZWVkIiwiaWF0IjoxNzIxODE1NjczfQ.OUQUKo1_dfrhZ-Y6eNMXwq80l5wJ-tiaSPj6w_RGcbw
content-type: application/json

  {
    "title": "melikedi's blog 1",
    "author": "melike",
    "url": "www.ddd.com",
    "likes": 1
  }

###
POST http://localhost:3001/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3RAZ21haWwuY29tIiwiaWQiOiI2NmEwZDIxNTIxMWE4MjJkMjlkNzdlZWYiLCJpYXQiOjE3MjE4MTU3MzB9.eD9q-PO-3CuHjpQqSdxsmZk1quK3ofKrfmKJGbDARHM
content-type: application/json

  {
    "title": "root's blog1",
    "author": "root",
    "url": "www.aaa.com",
    "likes": 1
  }
###
POST http://localhost:3001/api/blogs
content-type: application/json

{
            "title": "New Blog Test",
            "author": "New Blog Test Author",
            "url": "http://newblogtest.com",
            "likes": 12
        }
###
PUT http://localhost:3001/api/blogs/66ec297242bf5fe35cbddf66
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1lbGlrZWRpQGdtYWlsLmNvbSIsImlkIjoiNjZhMGQyMTMyMTFhODIyZDI5ZDc3ZWVkIiwiaWF0IjoxNzIxODE1NjczfQ.OUQUKo1_dfrhZ-Y6eNMXwq80l5wJ-tiaSPj6w_RGcbw
content-type: application/json

{
    "title": "9",
    "author": "9",
    "url": "9",
    "likes": 9,
    "user": "66a0d213211a822d29d77eed",
    "id": "66a7f60047f3fd59bdea6618"
  }