###
GET   http://localhost:3001/api/users

###
DELETE   http://localhost:3001/api/users/66a0d213211a822d29d77eed

###
POST http://localhost:3001/api/users
content-type: application/json

{
    "username": "user3@gmail.com",
    "name": "Venla Luuska",
    "password": "aurora"
}
###
POST http://localhost:3001/api/users
content-type: application/json

{
    "username": "root@gmail.com",
    "name": "root",
    "password": "aurora"
}
###
POST http://localhost:3001/api/users
content-type: application/json

  {
    "name": "melike",
  }
###
POST http://localhost:3001/api/testing/reset

